server:
  servlet:
    session:
      timeout: 120m
      cookie:
        name: JSESSIONID
        http-only: true
        same-site: strict

spring:
  thymeleaf:
    encoding: UTF-8
  application:
    name: AlgorithmCampus
  profiles:
    default: dev
    group:
      local: local
      dev: dev
      prod: prod
      test: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, metrics
  metrics:
    tags:
      application: ${spring.application.name}-${spring.profiles.active:local}
  endpoint:
    health:
      probes:
        enabled: true